export const ACCESS_TOKEN_EXPIRY = 30 * 60;
export const REFRESH_TOKEN_EXPIRY = 7 * 24 * 60 * 60;

export const ACCESS_TOKEN_EXPIRY_MS = ACCESS_TOKEN_EXPIRY * 1000;
export const REFRESH_TOKEN_EXPIRY_MS = REFRESH_TOKEN_EXPIRY * 1000;
